const coursesData = {
  Dentist: [
    {
      id: 1,
      expiry: 7,
      title: "Dental Surgery Basics",
      createdBy: "Dr. Smith",
      price: 49,
      description:
        "A complete guide to the fundamental principles of dental surgery, covering essential tools, procedural techniques, and patient safety protocols. Learn how to manage surgical environments and ensure optimal outcomes for various dental operations.",
      img: "https://toothfairyapp.co.uk/wp-content/uploads/african-american-man-patient-dental-chair-dentist-office-doctor-practice-concept-professional-dentist-helping-his-patient-dentistry-medical-drilling-patient-s-teeth-clinic-1-scaled.jpg",
    },
    {
      id: 2,
      expiry: 7,
      title: "Root Canal Mastery",
      createdBy: "Dr. Allen",
      price: 59,
      description: "Step-by-step mastery of root canal therapy, including advanced instrumentation, irrigation techniques, and case-based discussions. Understand how to diagnose pulp diseases and perform endodontic treatments with precision.",
      img: "https://toothfairyapp.co.uk/wp-content/uploads/african-american-man-patient-dental-chair-dentist-office-doctor-practice-concept-professional-dentist-helping-his-patient-dentistry-medical-drilling-patient-s-teeth-clinic-1-scaled.jpg",
    },
    {
      id: 3,
      expiry: 7,
      title: "Teeth Whitening Techniques",
      createdBy: "Dr. Lee",
      price: 39,
      description: "Learn professional teeth whitening methods using peroxide-based agents, laser-assisted techniques, and custom trays. Explore the science behind enamel safety and long-term effectiveness for different patient profiles.",
      img: "https://toothfairyapp.co.uk/wp-content/uploads/african-american-man-patient-dental-chair-dentist-office-doctor-practice-concept-professional-dentist-helping-his-patient-dentistry-medical-drilling-patient-s-teeth-clinic-1-scaled.jpg",
    },
    {
      id: 4,
      expiry: 7,
      title: "Oral Hygiene Essentials",
      createdBy: "Dr. Patel",
      price: 29,
      description:
        "Understand the essentials of oral hygiene, including brushing techniques, flossing habits, and the role of fluoride. Learn how to educate patients for better daily care and prevent common dental issues like plaque and gingivitis.",
      img: "https://toothfairyapp.co.uk/wp-content/uploads/african-american-man-patient-dental-chair-dentist-office-doctor-practice-concept-professional-dentist-helping-his-patient-dentistry-medical-drilling-patient-s-teeth-clinic-1-scaled.jpg",
    },
    {
      id: 5,
      expiry: 7,
      title: "Dental Implants Guide",
      createdBy: "Dr. Brown",
      price: 69,
      description:
        "Comprehensive training on dental implants, from initial diagnosis and bone assessment to surgical placement and post-operative maintenance. Explore implant materials, osseointegration, and long-term success strategies.",
      img: "https://toothfairyapp.co.uk/wp-content/uploads/african-american-man-patient-dental-chair-dentist-office-doctor-practice-concept-professional-dentist-helping-his-patient-dentistry-medical-drilling-patient-s-teeth-clinic-1-scaled.jpg",
    },
    {
      id: 6,
      expiry: 7,
      title: "Pediatric Dentistry",
      createdBy: "Dr. Green",
      price: 55,
      description: "Focused training in pediatric dentistry, dealing with children’s unique dental anatomy, behavior management, and preventive care. Learn how to create a child-friendly clinic environment and handle early orthodontic needs.",
      img: "https://toothfairyapp.co.uk/wp-content/uploads/african-american-man-patient-dental-chair-dentist-office-doctor-practice-concept-professional-dentist-helping-his-patient-dentistry-medical-drilling-patient-s-teeth-clinic-1-scaled.jpg",
    },
  ],
  "Gynecologist/obstetrician": [
    {
      id: 1,
      expiry: 7,
      title: "Prenatal Care Basics",
      createdBy: "Dr. Johnson",
      price: 49,
      description: "Covers all stages of prenatal care, from conception to delivery, ensuring a healthy pregnancy journey for both mother and child. Learn fetal monitoring, nutritional guidance, and emotional support strategies.",
      img: "https://tse1.explicit.bing.net/th/id/OIP.W2VIbw_FJTmyqsAx53PGvgHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 2,
      expiry: 7,
      title: "High-Risk Pregnancy",
      createdBy: "Dr. Evans",
      price: 69,
      description: "Practical approaches to identifying and managing high-risk pregnancies, including gestational diabetes, preeclampsia, and multiple gestations. Understand how to coordinate care across specialties and respond to complications.",
      img: "https://tse1.explicit.bing.net/th/id/OIP.W2VIbw_FJTmyqsAx53PGvgHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 3,
      expiry: 7,
      title: "Obstetric Emergencies",
      createdBy: "Dr. White",
      price: 79,
      description: "Training to handle critical obstetric emergencies such as postpartum hemorrhage, shoulder dystocia, and eclampsia. Gain confidence in rapid decision-making and emergency protocols in labor wards.",
      img: "https://tse1.explicit.bing.net/th/id/OIP.W2VIbw_FJTmyqsAx53PGvgHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 4,
      expiry: 7,
      title: "Infertility Treatments",
      createdBy: "Dr. Young",
      price: 59,
      description: "In-depth overview of infertility treatments, including IUI, IVF, and hormonal therapies. Explore reproductive technologies and counseling techniques for couples facing fertility challenges.",
      img: "https://tse1.explicit.bing.net/th/id/OIP.W2VIbw_FJTmyqsAx53PGvgHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 5,
      expiry: 7,
      title: "Menstrual Disorders",
      createdBy: "Dr. Hill",
      price: 45,
      description: "Diagnosis and management of menstrual disorders affecting women of all ages, from adolescence to menopause. Learn to treat conditions like PCOS, amenorrhea, and dysmenorrhea with both medical and lifestyle interventions.",
      img: "https://tse1.explicit.bing.net/th/id/OIP.W2VIbw_FJTmyqsAx53PGvgHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 6,
      expiry: 7,
      title: "Postnatal Care",
      createdBy: "Dr. King",
      price: 39,
      description: "Guidelines for effective postnatal care, addressing physical recovery, breastfeeding support, and mental health screening. Understand how to monitor maternal well-being and promote bonding with the newborn.",
      img: "https://tse1.explicit.bing.net/th/id/OIP.W2VIbw_FJTmyqsAx53PGvgHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
  ],

  "General Physician": [
    {
      id: 1,
      expiry: 7,
      title: "Primary Healthcare Basics",
      createdBy: "Dr. Adams",
      price: 39,
      description: "Introduction to primary healthcare practices and patient-centered care, focusing on preventive medicine and early diagnosis. Learn how to build trust and long-term relationships with patients across demographics.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 2,
      expiry: 7,
      title: "Hypertension Management",
      createdBy: "Dr. Davis",
      price: 49,
      description: "Evidence-based techniques for diagnosing and treating hypertension, including lifestyle modifications, pharmacological options, and monitoring strategies. Understand the impact of comorbidities and patient adherence.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 3,
      expiry: 7,
      title: "Diabetes Control",
      createdBy: "Dr. Wilson",
      price: 59,
      description: "Guidelines on lifestyle, diet, and medication for managing diabetes, with emphasis on glycemic control, insulin therapy, and patient education. Explore complications like neuropathy and retinopathy.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 4,
      expiry: 7,
      title: "Common Infectious Diseases",
      createdBy: "Dr. Martin",
      price: 45,
      description: "Diagnosis and treatment of common infectious diseases across age groups, including respiratory infections, gastrointestinal illnesses, and vector-borne diseases. Learn to interpret lab results and prescribe appropriate antimicrobials.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 5,
      expiry: 7,
      title: "Emergency Medicine Essentials",
      createdBy: "Dr. Lopez",
      price: 69,
      description: "Learn to handle medical emergencies and urgent care situations effectively, from cardiac arrest to anaphylaxis. Gain skills in triage, stabilization, and referral protocols.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 6,
      expiry: 7,
      title: "Family Medicine Overview",
      createdBy: "Dr. Walker",
      price: 55,
      description: "Comprehensive understanding of family medicine and holistic care, integrating physical, emotional, and social health. Explore chronic disease management and continuity of care across generations.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
  ],
  Dermatologist: [
    {
      id: 1,
      expiry: 7,
      title: "Skin Care Basics",
      createdBy: "Dr. Allen",
      price: 39,
      description: "Basic skin care practices for prevention and maintenance of healthy skin, including cleansing routines, moisturization, and sun protection. Learn how to tailor regimens for different skin types and conditions.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 2,
      expiry: 7,
      title: "Acne Treatments",
      createdBy: "Dr. Clark",
      price: 49,
      description: "Clinical approaches to treating acne and preventing recurrence, using topical agents, oral medications, and procedural interventions. Understand hormonal influences and psychological impacts.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 3,
      expiry: 7,
      title: "Psoriasis & Eczema",
      createdBy: "Dr. Lewis",
      price: 59,
      description: "Management of chronic skin conditions such as eczema and psoriasis, with insights into immunomodulatory therapies, lifestyle triggers, and patient counseling. Explore long-term care strategies and flare prevention.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 4,
      expiry: 7,
      title: "Laser Dermatology",
      createdBy: "Dr. Hall",
      price: 69,
      description: "Hands-on training in advanced laser-based dermatology procedures, including hair removal, pigmentation correction, and scar treatment. Learn safety protocols and post-procedure care.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 5,
      expiry: 7,
      title: "Cosmetic Dermatology",
      createdBy: "Dr. Allen",
      price: 79,
      description: "Aesthetic and cosmetic dermatology for enhancing patient confidence, covering botox, fillers, chemical peels, and skin rejuvenation. Understand ethical considerations and patient expectations.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
    {
      id: 6,
      expiry: 7,
      title: "Pediatric Dermatology",
      createdBy: "Dr. Scott",
      price: 55,
      description: "Pediatric dermatology focusing on children’s skin issues and treatments, such as diaper rash, birthmarks, and atopic dermatitis. Learn age-appropriate therapies and parental guidance techniques.",
      img: "https://www.orthobethesda.com/wp-content/uploads/2020/12/What-is-a-Sports-Medicine-Physician.jpg",
    },
  ],
  "Ear-nose-throat(ent) Specialist": [
    {
      id: 1,
      expiry: 7,
      title: "ENT Anatomy Basics",
      createdBy: "Dr. Parker",
      price: 39,
      description: "Detailed overview of ENT anatomy and its clinical significance, including the auditory system, nasal passages, and laryngeal structures. Learn how anatomical knowledge informs diagnosis and surgical planning.",
      img: "https://healthinfo.healthengine.com.au/assets/iStock-1051318054-1024x683.jpg",
    },
    {
      id: 2,
      expiry: 7,
      title: "Hearing Loss Treatments",
      createdBy: "Dr. Campbell",
      price: 49,
      description: "Diagnosis and treatment methods for patients with hearing loss, from audiometry to cochlear implants. Understand causes like otosclerosis, infections, and age-related degeneration.",
      img: "https://healthinfo.healthengine.com.au/assets/iStock-1051318054-1024x683.jpg",
    },
    {
      id: 3,
      expiry: 7,
      title: "Allergic Rhinitis",
      createdBy: "Dr. Rivera",
      price: 45,
      description: "Causes, symptoms, and treatments of allergic rhinitis and sinus issues, including antihistamines, nasal sprays, and surgical options. Learn how to differentiate between allergic and infectious presentations.",
      img: "https://healthinfo.healthengine.com.au/assets/iStock-1051318054-1024x683.jpg",
    },
    {
      id: 4,
      expiry: 7,
      title: "Sinus Surgery",
      createdBy: "Dr. Murphy",
      price: 59,
      description: "Practical surgical training for managing chronic sinus conditions, such as endoscopic sinus surgery and balloon sinuplasty. Explore pre-op evaluation and post-op care.",
      img: "https://healthinfo.healthengine.com.au/assets/iStock-1051318054-1024x683.jpg",
    },
    {
      id: 5,
      expiry: 7,
      title: "Voice Disorders",
      createdBy: "Dr. Bailey",
      price: 69,
      description: "Care and rehabilitation methods for patients with voice disorders, including vocal cord paralysis, nodules, and functional dysphonia. Learn therapy techniques and surgical interventions.",
      img: "https://healthinfo.healthengine.com.au/assets/iStock-1051318054-1024x683.jpg",
    },
    {
      id: 6,
      expiry: 7,
      title: "Sleep Apnea Management",
      createdBy: "Dr. Cooper",
      price: 75,
      description: "Approaches to diagnosing and managing sleep apnea through ENT, including CPAP therapy, uvulopalatopharyngoplasty, and lifestyle changes. Understand the link between airway anatomy and sleep quality.",
      img: "https://healthinfo.healthengine.com.au/assets/iStock-1051318054-1024x683.jpg",
    },
  ],
  Homoeopath: [
    {
      id: 1,
      expiry: 7,
      title: "Introduction to Homoeopathy",
      createdBy: "Dr. Morgan",
      price: 29,
      description: "Foundational concepts of homoeopathy and its holistic approach to health, emphasizing the law of similars and individualized treatment. Learn the philosophy behind remedy selection and patient evaluation.",
      img: "https://tse4.mm.bing.net/th/id/OIP.no0GPHVluikFW2ee1P4VIQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 2,
      expiry: 7,
      title: "Remedies for Common Cold",
      createdBy: "Dr. Bell",
      price: 35,
      description: "Practical home remedies for managing colds, flu, and seasonal illnesses, using common substances like Belladonna, Aconite, and Bryonia. Understand dosage, potency, and symptom matching.",
      img: "https://tse4.mm.bing.net/th/id/OIP.no0GPHVluikFW2ee1P4VIQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 3,
      expiry: 7,
      title: "Chronic Disease Management",
      createdBy: "Dr. Reed",
      price: 49,
      description: "Homoeopathic strategies for long-term chronic disease management, including arthritis, migraines, and digestive disorders. Explore constitutional remedies and case follow-ups.",
      img: "https://tse4.mm.bing.net/th/id/OIP.no0GPHVluikFW2ee1P4VIQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 4,
      expiry: 7,
      title: "Homeopathic Pharmacy",
      createdBy: "Dr. Cook",
      price: 45,
      description: "Pharmacy skills for preparing and handling homeopathic remedies, including dilution techniques, succussion, and storage protocols. Learn regulatory standards and safety practices.",
      img: "https://tse4.mm.bing.net/th/id/OIP.no0GPHVluikFW2ee1P4VIQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 5,
      expiry: 7,
      title: "Case Studies in Homoeopathy",
      createdBy: "Dr. Brooks",
      price: 55,
      description: "Case-based learning for applying homoeopathy in real scenarios, with detailed patient histories, remedy selection, and outcome tracking. Develop clinical reasoning and documentation skills.",
      img: "https://tse4.mm.bing.net/th/id/OIP.no0GPHVluikFW2ee1P4VIQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
    {
      id: 6,
      expiry: 7,
      title: "Advanced Materia Medica",
      createdBy: "Dr. Ward",
      price: 65,
      description: "Advanced Materia Medica and its applications in clinical settings, exploring remedy profiles, keynotes, and comparative analysis. Deepen your understanding of remedy relationships and miasmatic theory.",
      img: "https://tse4.mm.bing.net/th/id/OIP.no0GPHVluikFW2ee1P4VIQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
    },
  ],
  Ayurveda: [
    {
      id: 1,
      expiry: 7,
      title: "Basics of Ayurveda",
      createdBy: "Dr. Shah",
      price: 29,
      description: "Learn the principles of Ayurveda and its role in modern healthcare, including the concept of doshas, dhatus, and the five elements. Understand how to assess prakriti and vikriti in patients.",
      img: "https://th.bing.com/th/id/R.de24b88f4d2dde8419688153e2dede56?rik=aTT4oqifGl%2bSow&riu=http%3a%2f%2fwww.deepayurveda.com.au%2fcdn%2fshop%2farticles%2fa02c62e32f7f60eb165583126298dd2a.jpg%3fv%3d1693280186&ehk=4rYyWvXdHjLPI4oTyuWcadkyFi2PBbUtkRnYLIzl068%3d&risl=&pid=ImgRaw&r=0",
    },
    {
      id: 2,
      expiry: 7,
      title: "Ayurvedic Diet & Nutrition",
      createdBy: "Dr. Mehta",
      price: 39,
      description: "Dietary practices and nutrition guidelines rooted in Ayurveda, focusing on seasonal eating, digestive fire (Agni), and food compatibility. Learn how to create personalized meal plans.",
      img: "https://th.bing.com/th/id/R.de24b88f4d2dde8419688153e2dede56?rik=aTT4oqifGl%2bSow&riu=http%3a%2f%2fwww.deepayurveda.com.au%2fcdn%2fshop%2farticles%2fa02c62e32f7f60eb165583126298dd2a.jpg%3fv%3d1693280186&ehk=4rYyWvXdHjLPI4oTyuWcadkyFi2PBbUtkRnYLIzl068%3d&risl=&pid=ImgRaw&r=0",
    },
    {
      id: 3,
      expiry: 7,
      title: "Panchakarma Therapy",
      createdBy: "Dr. Nair",
      price: 49,
      description: "Medicinal properties and uses of common Ayurvedic herbs like Ashwagandha, Triphala, and Brahmi. Learn how to prepare decoctions, churnas, and oils for therapeutic use.",
      img: "https://th.bing.com/th/id/R.de24b88f4d2dde8419688153e2dede56?rik=aTT4oqifGl%2bSow&riu=http%3a%2f%2fwww.deepayurveda.com.au%2fcdn%2fshop%2farticles%2fa02c62e32f7f60eb165583126298dd2a.jpg%3fv%3d1693280186&ehk=4rYyWvXdHjLPI4oTyuWcadkyFi2PBbUtkRnYLIzl068%3d&risl=&pid=ImgRaw&r=0",
    },
    {
      id: 4,
      expiry: 7,
      title: "Ayurvedic Herbs",
      createdBy: "Dr. Iyer",
      price: 45,
      description: "Integrating yoga and Ayurveda for balanced health and wellness, combining physical postures, breathing techniques, and meditation. Understand how to align body, mind, and spirit.",
      img: "https://th.bing.com/th/id/R.de24b88f4d2dde8419688153e2dede56?rik=aTT4oqifGl%2bSow&riu=http%3a%2f%2fwww.deepayurveda.com.au%2fcdn%2fshop%2farticles%2fa02c62e32f7f60eb165583126298dd2a.jpg%3fv%3d1693280186&ehk=4rYyWvXdHjLPI4oTyuWcadkyFi2PBbUtkRnYLIzl068%3d&risl=&pid=ImgRaw&r=0",
    },
    {
      id: 5,
      expiry: 7,
      title: "Yoga & Ayurveda",
      createdBy: "Dr. Menon",
      price: 55,
      description: "A holistic approach to achieving harmony of mind, body, and spirit through Ayurvedic philosophy, lifestyle routines, and spiritual practices. Explore daily rituals (Dinacharya) and seasonal regimens (Ritucharya).",
      img: "https://th.bing.com/th/id/R.de24b88f4d2dde8419688153e2dede56?rik=aTT4oqifGl%2bSow&riu=http%3a%2f%2fwww.deepayurveda.com.au%2fcdn%2fshop%2farticles%2fa02c62e32f7f60eb165583126298dd2a.jpg%3fv%3d1693280186&ehk=4rYyWvXdHjLPI4oTyuWcadkyFi2PBbUtkRnYLIzl068%3d&risl=&pid=ImgRaw&r=0",
    },
    {
      id: 6,
      expiry: 7,
      title: "Holistic Healing",
      createdBy: "Dr. Pillai",
      price: 65,
      description: "Detoxification and rejuvenation techniques with Panchakarma therapy, including Vamana, Virechana, Basti, Nasya, and Raktamokshana. Explore indications, contraindications, and post-therapy care.",
      img: "https://th.bing.com/th/id/R.de24b88f4d2dde8419688153e2dede56?rik=aTT4oqifGl%2bSow&riu=http%3a%2f%2fwww.deepayurveda.com.au%2fcdn%2fshop%2farticles%2fa02c62e32f7f60eb165583126298dd2a.jpg%3fv%3d1693280186&ehk=4rYyWvXdHjLPI4oTyuWcadkyFi2PBbUtkRnYLIzl068%3d&risl=&pid=ImgRaw&r=0",
    },
  ],
};

export default coursesData;
