import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './global.css';
import { ClientProvider } from "@/components/ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  //  icons: {
  //   icon: `${basePath}/favicon.ico`,
  //   shortcut: `${basePath}/favicon.ico`,
  //   apple: `${basePath}/apple-touch-icon.png`,
  //   other: [
  //     { rel: "icon", url: `${basePath}/icon-32x32.png`, sizes: "32x32" },
  //     { rel: "icon", url: `${basePath}/icon-192x192.png`, sizes: "192x192" },
  //   ],
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
         <ClientProvider>
          {children}
         </ClientProvider>
      </body>
    </html>
  );
}
